# Generated by Django 5.1.3 on 2024-11-26 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_volunteer_task_volunteers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
